DOCKERIGNORE_COMMON = [
    ".git/",
    ".github/",
    ".gitignore",
    ".gitattributes",
    ".env",
    ".env.*",
    "*.log",
    "*.log.*",
    "README.md",
    "README.*",
    "CHANGELOG.md",
    "LICENSE",
    "Makefile",
    ".idea/",
    ".vscode/",
    ".sublime-project",
    ".sublime-workspace",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*.swo",
    "*~",
    ".claude/",
    "*.md",
]

DOCKERIGNORE_NODE = [
    "node_modules/",
    "dist/",
    "build/",
    "out/",
    ".cache/",
    ".next/",
    ".nuxt/",
    "coverage/",
    ".nyc_output/",
    ".eslintcache",
    "*.tgz",
    "*.tar.gz",
    ".npm/",
    ".yarn/",
    ".yarn-integrity",
]

DOCKERIGNORE_PYTHON = [
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".tox/",
    "*.egg-info/",
    "*.egg",
    "dist/",
    "build/",
    ".venv/",
    "venv/",
    "env/",
    ".Python",
    "pip-log.txt",
    "pip-delete-this-directory.txt",
]

DOCKERIGNORE_JAVA_GRADLE = [
    ".gradle/",
    "build/",
    "*.class",
    "*.war",
    "*.ear",
]

DOCKERIGNORE_JAVA_MAVEN = [
    "target/",
    "*.class",
    "*.war",
    "*.ear",
    ".mvn/",
]

BUILD_REQUIRED_PATHS = {
    "package.json",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "requirements.txt",
    "pyproject.toml",
    "poetry.lock",
    "Pipfile",
    "Pipfile.lock",
    "uv.lock",
    "pom.xml",
    "mvnw",
    "mvnw.cmd",
    ".mvn/wrapper/maven-wrapper.jar",
    "build.gradle",
    "build.gradle.kts",
    "settings.gradle",
    "settings.gradle.kts",
    "gradlew",
    "gradlew.bat",
    "gradle/wrapper/gradle-wrapper.jar",
    "go.mod",
    "go.sum",
}

OPTIONAL_NODE_COPY_FILES = {
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
}


NEXT_ROUTE_DIRS = (
    "app",
    "pages",
    "src/app",
    "src/pages",
)

STACK_PATTERNS = {
    "nextjs": {
        "detector": ["next.config.js", "next.config.mjs", "next.config.ts"],
        "secondary": ["package.json"],
        "score": 100,
        "expose": "3000",
        "cmd": None,
    },
    "nuxt": {
        "detector": ["nuxt.config.js", "nuxt.config.ts"],
        "secondary": ["package.json"],
        "score": 100,
        "expose": "3000",
        "cmd": None,
    },
    "vue": {
        "detector": ["vue.config.js", "vue.config.ts"],
        "secondary": ["package.json"],
        "score": 90,
        "expose": "3000",
        "cmd": None,
    },
    "svelte": {
        "detector": ["svelte.config.js", "svelte.config.ts"],
        "secondary": ["package.json"],
        "score": 90,
        "expose": "3000",
        "cmd": None,
    },
    "astro": {
        "detector": ["astro.config.js", "astro.config.mjs", "astro.config.ts"],
        "secondary": ["package.json"],
        "score": 90,
        "expose": "3000",
        "cmd": None,
    },
    "vite-static": {
        "detector": ["vite.config.js", "vite.config.ts"],
        "secondary": ["package.json"],
        "score": 80,
        "expose": "3000",
        "cmd": "serve -s dist -l 3000",
    },
    "node-static": {
        "detector": [],
        "secondary": ["package.json"],
        "score": 70,
        "expose": "3000",
        "cmd": "serve -s dist -l 3000",
    },
    "node-server": {
        "detector": ["server.js", "app.js", "index.js"],
        "secondary": ["package.json"],
        "score": 60,
        "expose": "3000",
        "cmd": None,
    },
    "python-fastapi": {
        "detector": ["main.py"],
        "secondary": ["requirements.txt", "pyproject.toml"],
        "score": 80,
        "expose": "8000",
        "cmd": "uvicorn main:app --host 0.0.0.0 --port 8000",
    },
    "python-flask": {
        "detector": ["app.py"],
        "secondary": ["requirements.txt", "pyproject.toml"],
        "score": 70,
        "expose": "5000",
        "cmd": "flask run --host 0.0.0.0 --port 5000",
    },
    "java-gradle": {
        "detector": ["build.gradle", "build.gradle.kts"],
        "secondary": ["settings.gradle"],
        "score": 80,
        "expose": "8080",
        "cmd": None,
    },
    "java-maven": {
        "detector": ["pom.xml"],
        "secondary": [],
        "score": 80,
        "expose": "8080",
        "cmd": None,
    },
    "go": {
        "detector": ["go.mod"],
        "secondary": [],
        "score": 80,
        "expose": "8080",
        "cmd": None,
    },
    "rust": {
        "detector": ["Cargo.toml"],
        "secondary": [],
        "score": 80,
        "expose": "8080",
        "cmd": None,
    },
    "ruby": {
        "detector": ["Gemfile"],
        "secondary": [],
        "score": 80,
        "expose": "3000",
        "cmd": None,
    },
    "php": {
        "detector": ["composer.json"],
        "secondary": [],
        "score": 80,
        "expose": "8000",
        "cmd": None,
    },
}
